[project]
name = "edu-course-companion"
version = "0.1.0"
description = "Project dedicated to creating educational course companion."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["content-extraction==0.3.1"]
